apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default
  source:
    # 1. غير هاد الرابط لرابط المستودع تبعك إنت على GitHub (Ops-Mastery-EKS)
    repoURL: https://github.com/tamer2004gf-ship-it/Ops-Mastery-EKS.git 
    targetRevision: main
    # 2. بما إن ملفاتك موجودة في الـ Root، بنخلي المسار نقطة "." أو نمسحه
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true