apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1. استدعاء المانيفست الأساسي من جيت هاب
  - https://github.com/GoogleCloudPlatform/microservices-demo.git/kubernetes-manifests?ref=main
  # 2. استدعاء ملف الـ loadgenerator برابط Raw مباشر عشان ما يعطي خطأ الـ Directory
  - https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/kubernetes-manifests/loadgenerator.yaml

images:
  - name: frontend
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/frontend
    newTag: latest
  - name: adservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/adservice
    newTag: latest
  - name: cartservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/cartservice
    newTag: latest
  - name: checkoutservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/checkoutservice
    newTag: latest
  - name: currencyservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/currencyservice
    newTag: latest
  - name: emailservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/emailservice
    newTag: latest
  - name: paymentservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/paymentservice
    newTag: latest
  - name: productcatalogservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/productcatalogservice
    newTag: latest
  - name: recommendationservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/recommendationservice
    newTag: latest
  - name: shippingservice
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/shippingservice
    newTag: latest
  - name: loadgenerator
    newName: 255621205478.dkr.ecr.eu-central-1.amazonaws.com/loadgenerator
    newTag: latest