apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  labels:
    release: kube-prometheus-stack # تأكد إن هاد الـ Label بيطابق اللي نزلته مع LGTM
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: http
    path: /metrics