apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: boutique-db-password-k8s  # هذا سيكون اسم السر داخل كوبرنيتس
    creationPolicy: Owner
  data:
  - secretKey: password             # المفتاح داخل كوبرنيتس
    remoteRef:
      key: boutique-db-password     # اسم السر في AWS Secrets Manager
      property: password            # المفتاح داخل السر في AWS