apiVersion: v1
data:
  overrides.yaml: |
    overrides:
      {}
  tempo.yaml: |
    memberlist:
      cluster_label: "tempo.monitoring"
    multitenancy_enabled: false
    usage_report:
      reporting_enabled: true
    compactor:
      compaction:
        block_retention: 24h
    distributor:
      receivers:
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_binary:
                  endpoint: 0.0.0.0:6832
                thrift_compact:
                  endpoint: 0.0.0.0:6831
                thrift_http:
                  endpoint: 0.0.0.0:14268
            opencensus: null
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
    ingester:
          {}
    server:
          http_listen_port: 3200
    storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal
    querier:
          {}
    query_frontend:
          {}
    overrides:
          defaults: {}
          per_tenant_override_config: /conf/overrides.yaml
    metrics_generator:
      processors: [service-graphs, span-metrics]
      storage:
        path: "/tmp/tempo"
        remote_write:
          - url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
      traces_storage:
        path: "/tmp/traces"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: tempo
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-03-27T10:49:32Z"
  labels:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.9.0
    helm.sh/chart: tempo-1.24.4
  name: tempo
  namespace: monitoring
  resourceVersion: "4357"
  uid: 8c2f377d-2612-4c6b-b0f2-e45afdc26e62
